version: '3.8'

services:
  bot:
    build: .
    container_name: ai-center-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot-network
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Uncomment for Phase 2+ when databases are needed
  # postgres:
  #   image: postgres:14
  #   container_name: ai-center-postgres
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - bot-network
  #   restart: unless-stopped
  
  # redis:
  #   image: redis:7
  #   container_name: ai-center-redis
  #   networks:
  #     - bot-network
  #   restart: unless-stopped

networks:
  bot-network:
    driver: bridge

# Uncomment for Phase 2+ when databases are needed
# volumes:
#   postgres-data: